spring.application.name=payment_service
server.port = 8086

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

payment.simulation.enabled=${PAYMENT_SIMULATION_ENABLED:true}
payment.simulation.delay-seconds=${PAYMENT_SIMULATION_DELAY_SECONDS:4}
payment.simulation.failure-rate=${PAYMENT_SIMULATION_FAILURE_RATE:0.0}